services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=${PUID:-950}
      - PGID=${PGID:-950}
      - TZ=${TZ:-Asia/Jerusalem}
    volumes:
      - ./config:/config
      - /mnt/Ochayon_Home_Data/apps/immich:/immich
      - /mnt/Ochayon_Home_Data/apps/code-server:/code-server
      - /mnt/Ochayon_Home_Data/apps/traefik-truenas:/traefik-truenas
      - /mnt/Ochayon_Home_Data/apps/dolev:/dolev
      - /mnt/Ochayon_Home_Data/apps/idrac-monitoring:/idrac-monitoring
      - /mnt/Ochayon_Home_Data/apps/truenas-minio:/truenas-minio
      - /mnt/Ochayon_Home_Data/apps/n8n-whatsapp:/n8n-whatsapp
      # - /mnt/Ochayon_Home_Data/apps/{}:/{}
    ports:
      - 8443:8443
    restart: unless-stopped